repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: forbid-conflict-backups
        name: Forbid conflict backup files
        language: system
        entry: bash
        pass_filenames: false
        stages: [pre-commit, pre-push]
        args:
          - -lc
          - >
            git diff --cached --name-only |
            grep -E '\.CONFLICT\.BAK$' &&
            echo 'ERROR: conflict backups must not be committed.' &&
            exit 1 || exit 0
