default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--output-format=github, --fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ascii-comments-strings
        name: Block non-ASCII in Python comments and strings
        entry: python3 scripts/check_ascii_pytext.py
        language: system
        types: [python]
        pass_filenames: true
        require_serial: true
        -   id: forbid-conflict-backups
    name: Forbid conflict/backup files
    entry: bash scripts/forbid_conflict_backups.sh
    language: system
    pass_filenames: false
    -   id: ascii-text
    name: Block non-ASCII in repo text files
    entry: bash scripts/check_ascii_text.sh
    language: system
    pass_filenames: true
    types_or: [text]
    exclude: |
      (?x)(
        ^\.git/|
        \.(png|jpg|jpeg|gif|ico|pdf|svg|db|sqlite3|zip|gz|bz2|xz|7z)$
      )


