[tool.ruff]
target-version = "py311"
line-length = 100
exclude = [".venv", ".git", ".ruff_cache", ".streamlit"]

[tool.ruff.lint]
select = ["E","F","I","UP","B","SIM","PL","RUF"]
ignore = ["E203","E266","E501","PLR0912","PLR0913","PLR0915"]

[tool.ruff.lint.isort]
known-first-party = ["app_admin"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
