name: auto-format

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff==0.6.9

      - name: Run ruff format (write changes)
        run: ruff format .

      - name: Show diff (for audit)
        run: git diff --stat || true

      - name: Create PR with formatted files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "style: ruff format"
          branch: "ci/ruff-format-${{ github.run_id }}"
          title: "style: ruff format"
          body: "Automated Ruff code formatting."
          labels: "ci,style"
          delete-branch: true

